#!/bin/sh

#     DESCRIPTION
#
# Turn On/Off services on system startup/shutdown.


#     REQUIRES
#


#     INFO
#

NAME="init3-services"

verbose()
{
    if [ -n "$GLOBAL_VERBOSE" ]; then
        echo "HOOK: $NAME: $@"
    fi
}

verbose "has started"

/sbin/chkconfig network on ||:
/sbin/chkconfig portmap on ||:
/sbin/chkconfig random on ||:
/sbin/chkconfig livecd-setlocale on ||:
/sbin/chkconfig clamd off ||:
/sbin/chkconfig dhcpd off ||:
/sbin/chkconfig sshd off ||:
/sbin/chkconfig openvpn off ||:
/sbin/chkconfig NetworkManager on ||:
/sbin/chkconfig livecd-hostname on ||:
/sbin/chkconfig livecd-save-nfs on ||:

# HAL replace acpid:
/sbin/chkconfig acpid off ||:

/sbin/chkconfig smartd off ||:
/sbin/chkconfig bridge off ||:
/sbin/chkconfig crond off ||:
/sbin/chkconfig anacron off ||:
/sbin/chkconfig rawdevices off ||:
/sbin/chkconfig update_wms off ||:
/sbin/chkconfig xinetd off ||:
/sbin/chkconfig mdadm off ||:
/sbin/chkconfig netfs off ||:


# populate /etc/fstab with non-removable FS
/sbin/chkconfig livecd-fstab on ||:

# livecd-evms - used in livecd-restore, livecd-install
/sbin/chkconfig livecd-evms on ||:

# XXX(stanv): sem@ suggest turn off dnsmasq service at startup
# NetworkManager can invoke dnsqmasq by self:
# https://bugzilla.altlinux.org/show_bug.cgi?id=18799
/sbin/chkconfig dnsmasq off ||:

verbose "finished"
