default: all

all: dvd lite-cd

dvd: /home/inter/out/antique/dvd-i586-ru-$(DATE).iso
	./test-iso /home/inter/out/antique/dvd-i586-ru-$(DATE).iso dvd

lite-cd: /home/inter/out/antique/altlinux-4.0.3-$(DATE)-lite-i586-ru-CD.iso
	./test-iso /home/inter/out/antique/altlinux-4.0.3-$(DATE)-lite-i586-ru-CD.iso lite-cd

