#!/bin/sh

LOADER_SUFFIX=
[ "$INFO_BOOT_TYPE" = syslinux ] && LOADER_SUFFIX=.syslinux

cd "$WORKDIR"
exec >syslinux/$INFO_BOOT_TYPE.cfg

cat ../.in/isolinux/common

if [ -r altinst ] ; then
	size=$[ $(stat -c%s altinst) / 1000 +1 ]
	cat ../.in/isolinux/install$LOADER_SUFFIX | sed "s/@altinst_size@/$size/g"
fi

if [ -r rescue ] ; then
	size=$[ $(stat -c%s rescue) / 1000 +1 ]
	cat ../.in/isolinux/rescue$LOADER_SUFFIX |  sed "s/@rescue_size@/$size/g"
fi

[ -r live ] && cat ../.in/isolinux/live$LOADER_SUFFIX

[ -r syslinux/memtest ] && cat ../.in/isolinux/memtest

true
